### ISSUE TITLE
Greenhouses causes major TPS drops

### ISSUE THREAD

**Issue by Foorack** [tastybento/greenhouses#13]
![ekrankopio de 2018-04-27 18-03-02](https://user-images.githubusercontent.com/5008081/39373175-06ce5b72-4a47-11e8-97a6-b5934a191507.png)

When we disabled the plugin with `/plugman unload Greenhouses`

![ekrankopio de 2018-04-27 18-11-10](https://user-images.githubusercontent.com/5008081/39373205-1ddc531e-4a47-11e8-8113-4badc43f854f.png)

TPS skyrocketed and TPS-loss dropped. :thinking: 

Server version: Paper version git-Paper-1299 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Greenhouses version: 5.7

**Comment by tastybento** [comment]
The issue is being cause by flowing water (or lava) within greenhouses coupled with the check to see if the water is flowing into or out of the greenhouse. You can avoid the lag by changing the settings in config.yml to true like these:

```
   ### Default settings for greenhouse actions 
   # Allow lava or water to flow out of a greenhouse, e.g. through the door, floor
   allowflowout: true
   # Allow lava or water to flow into a greenhouse, e.g., through the door
   allowflowin: true
```

**Comment by Foorack** [comment]
This seems to have fixed it, thanks.
