### ISSUE TITLE
1.11 error

### ISSUE THREAD

**Issue by krustymk** [tastybento/greenhouses#6]
http://pastebin.com/MRv5KnW5

**Comment by tastybento** [comment]
Cheers. Yes, I haven't got to Greenhouses yet, but I will.

**Comment by krustymk** [comment]
No worries, thanks for keeping it up (if you know what i mean hahaha)

**Comment by krustymk** [comment]
Its growing tree's in the island nether that causes it

**Comment by tastybento** [comment]
Ah, this was fixed in V5.7:
https://www.spigotmc.org/resources/greenhouses.910/updates
